receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
      http:
        endpoint: '0.0.0.0:4318'
  faro:
    endpoint: '0.0.0.0:8081'
    cors:
      allowed_origins: "*"
processors:
  batch:
    timeout: 1s
exporters:
  debug:
    verbosity: detailed
service:
  extensions: [ ]
  pipelines:
    traces:
      receivers: [ faro ]
      processors: [ ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ debug ]
    logs:
      receivers: [ faro  ]
      processors: [ ]
      exporters: [ debug ]
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: json
